### ISSUE TITLE
Multiple constraints in one model

### ISSUE THREAD

**Issue by kumarmanas** [pylon-lib/pylon#21]
Can we have more than one constraints for the model. Say we have 2 different constraints, one constraints working for for specific set of samples of input and another working for rest of the samples or data. So can  Pylon handle such types of situation?

**Comment by KareemYousrii** [comment]
Sorry for the late reply @kumarmanas. The answer is Yes! You can have as many constraint losses as you wish. See for instance the Sudoku example, where we have a separate constraint for every row, column and square in the Sudoku puzzle.
